# Generated by Django 3.1.7 on 2021-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='kind',
            field=models.BooleanField(default=None, help_text='True = Like | False = Dislike', null=True),
        ),
    ]
