# Generated by Django 3.1.7 on 2021-04-05 17:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('avatar', models.ImageField(blank=True, default='', upload_to=core.models.make_upload_path)),
                ('last_request', models.DateTimeField(blank=True, help_text='When user make last request', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
