# Generated by Django 3.1.7 on 2021-04-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210417_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='api_url',
            new_name='url',
        ),
    ]
